stages:
    - test
    - build
    - deploy

test_redoc:
    stage: test
    image: daedalusproject/base_node8
    script:
        - npm install
        - npm test

build_api_docs:
    stage: build
    image: daedalusproject/base_node8
    script:
        - npm install
        - npm run build
    artifacts:
        paths:
        - web_deploy
        expire_in: 5 minutes


deploy_develop_image:
    stage: deploy
    image: docker:stable
    script:
        - ls -lahrt
    dependencies:
    - build_api_docs
