stages:
    - test
    - build

test_deploy:
    stage: test
    image: daedalusproject/base_node8
    script:
        - npm install
        - npm test

build_develop_image:
    stage: build
    image: daedalusproject/base_node8
    script:
        - npm install
        - npm run build
    artifacts:
        paths:
        - web_deploy
        expire_in: 10 minutes
