openapi: 3.0.0
info:
  version: 0.0.1
  title: Daedalus-Core
  contact:
    email: acastellano@daedalus-project.io
    url: 'https://daedalus-project.io/contact'
  license:
    name: GNU General Public License 3.0
    url: 'https://www.gnu.org/licenses/gpl-3.0.en.html'
  x-logo:
    url: 'https://apis.guru/openapi-template/logo.png'
  description: >
    This is the Daedalus Poject Core API specification.

    # Introduction

    This specification is intended to to be a good starting point for describing
    this API, offering developers examples for working with it.

externalDocs:
  description: Daedalus Project Docs
  url: 'https://readthedocs.org'
tags:
  - name: Ping
    description: Checks if service is working
  - name: Login
    description: User login
  - name: ImAdmin
    description: User imadmin
  - name: Register
    description: User register
  - name: Confirm
    description: Confirm user registration
  - name: ShowActive
    description: Show Active Users
  - name: ShowInactive
    description: Show Inactive Users
  - name: ShowRegistered
    description: Show Registered Users
  - name: ShowOrphan
    description: Show Orphan Users

servers:
  - url: 'https://api-dev.daedalus-project.io'
